# This builds Amiga hunk executables for Amiga OS 68000

CC=vbccm68k
COPTS=-D__AMIGA__ -cpu=68020 -fpu=68881 -O=991 -I. -I../amiga -I../pdpclib

bios.exe: bios.o exeload.o
  vlink -bamigahunk -o bios.exe ../pdpclib/amistart.o bios.o exeload.o ../pdpclib/pdpclib.lib

.c.o:
  $(CC) $(COPTS) -o=$*.s $<
  vasmm68k_mot -o $*.o -Fhunk $*.s
  rm -f $*.s
