/*********************************************************************/
/*                                                                   */
/*  This Program Written by Paul Edwards, kerravon@w3.to             */
/*  Released to the Public Domain                                    */
/*                                                                   */
/*********************************************************************/
/*********************************************************************/
/*                                                                   */
/*  dccrepl - replace DCC lines generated by GCC 3.2 with 370        */
/*  assembler.  Yes, it should really have been done as an           */
/*  assembler macro.  When I learn how to write assembler macros,    */
/*  I'll keep you in the loop. :-)                                   */
/*                                                                   */
/*********************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(void)
{
    char buf[200];
    char *c;
    char *d;
    char *e;
    char *f;
    char *p;
    int frame;
    int cindex;
    int csects = 0;

    while (fgets(buf, sizeof buf, stdin) != NULL)
    {
        d = strstr(buf, "DCCPRLG");
        if (d != NULL)
        {
            frame = 0;
            e = strstr(buf, "ENTRY=YES");
            f = strstr(buf, "FRAME");
            if (f != NULL)
            {
                frame = atoi(f + 6);
            }
            cindex = 0;
            c = strstr(buf, "CINDEX");
            if (c != NULL)
            {
                cindex = atoi(c + 7);
            }
            if (e != NULL)
            {
                p = strchr(buf, '\t');
                if (p != NULL)
                {
                    *p = '\0';
                    printf("\tENTRY\t%s\n", buf);
                    *p = '\t';
                }
            }
            strcpy(d, "CSECT\n");
            fputs(buf, stdout);
            printf("\tUSING\t*,12\n"); /*,7,8,9\n");*/
            printf("\tSAVE\t(14,12)");
            p = strchr(buf, '\t');
            if (p != NULL)
            {
                *p = '\0';
                printf(",,%s_&SYSDATE", buf);
                *p = '\t';
            }
            printf("\n");
            printf("\tLR\t12,15\n");
            
/*            printf("\tLA\t7,2048(12)\n");
            printf("\tLA\t7,2048(7)\n");
            printf("\tLA\t8,2048(7)\n");
            printf("\tLA\t8,2048(8)\n");
            printf("\tLA\t9,2048(8)\n");
            printf("\tLA\t9,2048(9)\n"); */
            
            printf("\tL\t15,76(13)\n");
            printf("\tST\t13,4(15)\n");
            printf("\tST\t15,8(13)\n");
            printf("\tLR\t13,15\n");
            printf("\tA\t15,=F'%d'\n", frame);
            printf("\tST\t15,76(13)\n");
        }
        else if ((d = strstr(buf, "DCCEPIL")) != NULL)
        {
            printf("\tL\t13,4(13)\n");
            strcpy(d, "RETURN (14,12),RC=(15)\n");
            fputs(buf, stdout);
        }
        else if (strncmp(buf, "@FRAMESIZE_", 11) == 0)
        {
            printf("*");
            buf[10] = '@';
            fputs(buf, stdout);
        }
        else if ((strstr(buf, "CSECT") != NULL)
                 && (strchr("@$", buf[0]) != NULL))
        {
            csects++;
            printf("*");
            fputs(buf, stdout);
            if (csects == 1)
            {
                printf("\tCSECT\n");
            }
        }
        else
        {
            fputs(buf, stdout);
        }
    }
    return (0);
}
